import "./globals.css";

//import components
import Footer from "@/components/Footer";
import Header from "@/components/Header";

//ThemeProvider
import { ThemeProvider } from "@/components/ThemeProvider";

//Font update
import { Sen } from "next/font/google";


const SenFont =Sen({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
  display: "swap"
})





export const metadata = {
  title: "Vconverter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={SenFont.className} >
        <ThemeProvider attribute="class" defaultTheme='light'> 
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
